[platformio]
default_envs = T-A7670X
;src_dir = examples/SendSMS

[env]
platform = espressif32@6.11.0
framework = arduino
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200

[esp32dev_base]
board = esp32dev
build_flags =
        ${env.build_flags}
        -mfix-esp32-psram-cache-issue
        -DBOARD_HAS_PSRAM  
monitor_filters =
        default
        esp32_exception_decoder

[esp32s3_base]
board = esp32s3box
build_flags =
    ${env.build_flags}
;     -UARDUINO_USB_CDC_ON_BOOT
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
monitor_filters =
        time
        default
        esp32_exception_decoder
    
[env:T-A7670X]
extends = esp32dev_base
build_flags = ${esp32dev_base.build_flags}
            -DLILYGO_T_A7670
            -DCORE_DEBUG_LEVEL=3
lib_deps = https://github.com/lewisxhe/TinyGSM-fork/archive/refs/tags/v1.0.0.zip