[platformio]
default_envs = X
;src_dir = examples/SendSMS

[env]
platform = espressif32@6.11.0
framework = arduino
monitor_speed = 115200

[esp32dev_base]
board = esp32dev
build_flags =
        ${env.build_flags}
        -mfix-esp32-psram-cache-issue
        -DBOARD_HAS_PSRAM  
        !python gitVersion.py
        
monitor_filters =
        default
        esp32_exception_decoder

  
[TA7670X]
extends = esp32dev_base
build_flags = ${esp32dev_base.build_flags}
            -DLILYGO_T_A7670
            -DCORE_DEBUG_LEVEL=3
lib_deps = https://github.com/lewisxhe/TinyGSM-fork/archive/refs/tags/v1.0.0.zip
           adafruit/DHT sensor library@1.4.4

[env:X]
extends = TA7670X
upload_port = COM9
monitor_port = COM9
build_flags =
        ${TA7670X.build_flags}
        -DX

[env:H]
extends = TA7670X
upload_port = COM3
monitor_port = COM3
build_flags =
        ${TA7670X.build_flags}
        -DH

[env:tests]
platform = native
framework =
test_framework = unity
test_build_src = yes
build_flags =
    -Itest/mocks
    -Iinclude
    -std=c++17
    -DBOARD_BAT_ADC_PIN=35
    -fprofile-arcs
    -ftest-coverage
    -lgcov
    -O0
build_src_filter = +<*> -<main.cpp>